16:33:16.969 INFO Test execution started: test_builder.add_description
16:33:16.970 INFO Browser: chrome
16:33:16.970 INFO Environment: test
16:33:16.970 INFO Using data: 
    url: http://localhost:8000

16:33:21.404 INFO Navigate to: 'http://localhost:8000'
16:33:22.311 INFO Write 'admin' in element username
16:33:22.464 INFO Write 'admin' in element password
16:33:22.544 INFO Click login_button
16:33:28.903 INFO Random value generated: gqhteay
16:33:28.904 INFO Store value gqhteay in key name
16:33:30.392 INFO Write 'gqhteay' in element None
16:33:30.394 INFO Press key: ENTER
16:33:30.624 INFO Click None
16:33:31.109 INFO Take screenshot error
16:33:32.223 ERROR An error ocurred:
Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/test_runner/test_runner.py", line 114, in run_test
    test_module.test(execution.data)
  File "/Users/lucianofeo/Desktop/golem/example/projects/golem/tests/test_builder/add_description.py", line 17, in test
    send_keys(test_page.description, data.description)
  File "/Users/lucianofeo/Desktop/golem/src/golem/actions.py", line 234, in send_keys
    webelement.send_keys(text)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webelement.py", line 351, in send_keys
    {'text': "".join(keys_to_typing(value)),
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/common/utils.py", line 150, in keys_to_typing
    for i in range(len(val)):
TypeError: object of type 'NoneType' has no len()
16:33:32.225 INFO Close driver
