11:29:03.901 INFO Test execution started: login.login_incorrect_password
11:29:03.902 INFO Browser: chrome
11:29:03.902 INFO Environment: test
11:29:03.903 INFO Using data: 
    url: http://localhost:8000

11:29:11.627 INFO Navigate to: 'http://localhost:8000'
11:29:11.798 INFO Write 'admin' in element username
11:29:14.671 INFO Write 'incorect password' in element password
11:29:14.742 INFO Click login_button
11:29:18.126 INFO Take screenshot Verify the correct error message is shown
11:37:53.912 INFO Take screenshot error
11:37:53.917 ERROR An error ocurred:
Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/test_runner/test_runner.py", line 114, in run_test
    test_module.test(execution.data)
  File "/Users/lucianofeo/Desktop/golem/example/projects/golem/tests/login/login_incorrect_password.py", line 14, in test
    capture('Verify the correct error message is shown')
  File "/Users/lucianofeo/Desktop/golem/src/golem/actions.py", line 83, in capture
    driver.get_screenshot_as_file(img_path)
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 896, in get_screenshot_as_file
    png = self.get_screenshot_as_png()
  File "/Users/lucianofeo/Desktop/golem/env/lib/python3.6/site-packages/selenium-3.6.0-py3.6.egg/selenium/webdriver/remote/webdriver.py", line 928, in get_screenshot_as_png
    return base64.b64decode(self.get_screenshot_as_base64().encode('ascii'))
AttributeError: 'NoneType' object has no attribute 'encode'
11:37:53.933 INFO Close driver
