21:08:13.058 INFO Test execution started: product.add_product_to_cart_go_to_checkout
21:08:13.059 INFO Browser: chrome-remote
21:08:13.063 ERROR An error ocurred:
Traceback (most recent call last):
  File "/Users/lucianofeo/Desktop/golem/src/golem/test_runner/test_runner.py", line 114, in run_test
    test_module.test(execution.data)
  File "/Users/lucianofeo/Desktop/golem/example/projects/store_demoqa/tests/product/add_product_to_cart_go_to_checkout.py", line 12, in test
    navigate('http://store.demoqa.com/')
  File "/Users/lucianofeo/Desktop/golem/src/golem/actions.py", line 145, in navigate
    driver = get_browser()
  File "/Users/lucianofeo/Desktop/golem/src/golem/browser.py", line 262, in get_browser
    elif driver_selected == 'ie':
NameError: name 'driver_selected' is not defined
